# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20171107_1951'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Article')),
                ('entry', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Entry')),
            ],
        ),
    ]
