# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-09 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171109_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
