# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-10 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171109_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='published',
            new_name='pub_date',
        ),
    ]
